# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 07:16
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agridata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('crop_year', models.IntegerField(max_length=11)),
                ('season', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('production', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('rainfall', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Agromain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.CharField(max_length=100)),
                ('active', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField(max_length=20)),
                ('user_id', models.IntegerField(max_length=11)),
            ],
        ),
    ]
