# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agridata',
            name='crop_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='agridata',
            name='rainfall',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='agromain',
            name='active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
