# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-06 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190301_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
