# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-18 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190306_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agromain',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
