# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-20 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190318_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agromain',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
    ]
