# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190320_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agridata',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agridata',
            name='crop_year',
            field=models.IntegerField(default=2002),
        ),
        migrations.AlterField(
            model_name='agridata',
            name='production',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agridata',
            name='rainfall',
            field=models.IntegerField(default=0),
        ),
    ]
