# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190328_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
