# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-28 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20190328_1325'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
