# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-29 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20190329_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
