# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-29 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20190329_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=80),
        ),
    ]
